-- MySQL Script generated by MySQL Workbench
-- Thu Jul 14 09:37:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mobility
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mobility` ;

-- -----------------------------------------------------
-- Schema mobility
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mobility` DEFAULT CHARACTER SET utf8 ;
USE `mobility` ;

-- -----------------------------------------------------
-- Table `mobility`.`ort`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`ort` ;

CREATE TABLE IF NOT EXISTS `mobility`.`ort` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plz` VARCHAR(45) NOT NULL,
  `stadt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `plz_UNIQUE` (`plz` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`rechnung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`rechnung` ;

CREATE TABLE IF NOT EXISTS `mobility`.`rechnung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preis` VARCHAR(45) NOT NULL,
  `datum` DATE NOT NULL,
  `anrede` VARCHAR(45) NOT NULL,
  `beschreibung` VARCHAR(255) NOT NULL,
  `bezahlt` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`person` ;

CREATE TABLE IF NOT EXISTS `mobility`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `vorname` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `tel_nummer` VARCHAR(45) NOT NULL,
  `ort_id` INT NOT NULL,
  `rechnung_id` INT NULL,
  `verantwortlicher_haushalt` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_person_ort_idx` (`ort_id` ASC) VISIBLE,
  INDEX `fk_person_rechnung1_idx` (`rechnung_id` ASC) VISIBLE,
  UNIQUE INDEX `tel_nummer_UNIQUE` (`tel_nummer` ASC) VISIBLE,
  UNIQUE INDEX `rechnung_id_UNIQUE` (`rechnung_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_ort`
    FOREIGN KEY (`ort_id`)
    REFERENCES `mobility`.`ort` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_rechnung1`
    FOREIGN KEY (`rechnung_id`)
    REFERENCES `mobility`.`rechnung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`abonnament_art`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`abonnament_art` ;

CREATE TABLE IF NOT EXISTS `mobility`.`abonnament_art` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `preis` VARCHAR(45) NOT NULL,
  `rabatt` VARCHAR(45) NULL,
  `beschreibung` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idabonnament_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`tarif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`tarif` ;

CREATE TABLE IF NOT EXISTS `mobility`.`tarif` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preis_pro_stunde_nacht` VARCHAR(45) NOT NULL,
  `preis_pro_stunde_tag` VARCHAR(45) NOT NULL,
  `kilomoter_unter_100` VARCHAR(45) NOT NULL,
  `kilometer_ueber_100` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`auto` ;

CREATE TABLE IF NOT EXISTS `mobility`.`auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `anz_personen` INT NOT NULL,
  `anz_koffer` VARCHAR(45) NOT NULL,
  `tarif_id` INT NOT NULL,
  `manual` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`, `tarif_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_auto_tarif1_idx` (`tarif_id` ASC) VISIBLE,
  CONSTRAINT `fk_auto_tarif1`
    FOREIGN KEY (`tarif_id`)
    REFERENCES `mobility`.`tarif` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`ausleihe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`ausleihe` ;

CREATE TABLE IF NOT EXISTS `mobility`.`ausleihe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_timestamp` TIMESTAMP NOT NULL,
  `end_timestamp` TIMESTAMP NOT NULL,
  `kilometer` INT NOT NULL,
  `rechnung_id` INT NOT NULL,
  `ort_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ausleihe_Rechnung1_idx` (`rechnung_id` ASC) VISIBLE,
  INDEX `fk_ausleihe_ort1_idx` (`ort_id` ASC) VISIBLE,
  UNIQUE INDEX `rechnung_id_UNIQUE` (`rechnung_id` ASC) VISIBLE,
  CONSTRAINT `rechnung:id`
    FOREIGN KEY (`rechnung_id`)
    REFERENCES `mobility`.`rechnung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ausleihe_ort1`
    FOREIGN KEY (`ort_id`)
    REFERENCES `mobility`.`ort` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`person_auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`person_auto` ;

CREATE TABLE IF NOT EXISTS `mobility`.`person_auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ausleihe_id` INT NOT NULL,
  `auto_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ausleihe_id`, `auto_id`, `person_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_person_auto_ausleihe1_idx` (`ausleihe_id` ASC) VISIBLE,
  UNIQUE INDEX `ausleihe_id_UNIQUE` (`ausleihe_id` ASC) VISIBLE,
  INDEX `fk_person_auto_auto1_idx` (`auto_id` ASC) VISIBLE,
  INDEX `fk_person_auto_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_auto_ausleihe1`
    FOREIGN KEY (`ausleihe_id`)
    REFERENCES `mobility`.`ausleihe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_auto_auto1`
    FOREIGN KEY (`auto_id`)
    REFERENCES `mobility`.`auto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_auto_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mobility`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`ermahnung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`ermahnung` ;

CREATE TABLE IF NOT EXISTS `mobility`.`ermahnung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `rechnung_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ermahnung_rechnung1_idx` (`rechnung_id` ASC) VISIBLE,
  CONSTRAINT `fk_ermahnung_rechnung1`
    FOREIGN KEY (`rechnung_id`)
    REFERENCES `mobility`.`rechnung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobility`.`dauer_abonamment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobility`.`dauer_abonamment` ;

CREATE TABLE IF NOT EXISTS `mobility`.`dauer_abonamment` (
  `person_id` INT NOT NULL,
  `abonnament_art_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  INDEX `fk_dauer_abonamment_person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_dauer_abonamment_abonnament_art1_idx` (`abonnament_art_id` ASC) VISIBLE,
  UNIQUE INDEX `person_id_UNIQUE` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_dauer_abonamment_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mobility`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dauer_abonamment_abonnament_art1`
    FOREIGN KEY (`abonnament_art_id`)
    REFERENCES `mobility`.`abonnament_art` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- All test data:
INSERT INTO `ort`(`plz`, `stadt`) VALUES 
  ('8134','Adlswil'),
  ('8038', 'Wollishofen');
INSERT INTO `abonnament_art`(`name`, `preis`, `rabatt`, `beschreibung`) VALUES 
  ('Jahresabo ohne ermässigung','290CHF', '', 'jahresabo ohne ermässigungen'),
  ('Jahresabo ohne ermässigung','290CHF', '100CHF', 'jahresabo mit ermässigungen von GA, Halbtax, Jahres-Streckenabo der SBB oder Jahreskarte vom lokalen Verkehrsbetrieb'),
  ('Jahresabo ohne ermässigung','145CHF', '50%', 'jahresabo mit Ermässigung gleichen Haushalt');
INSERT INTO `rechnung`(`preis`, `datum`, `anrede`, `beschreibung`, `bezahlt`) VALUES
  ('15.40CHF', DATE '2022-05-22', 'Alex Smolders', 'Autofahrt in der Zürich', 1),
  ('145CHF', DATE '2022-05-22', 'Severin Machaz', 'Abo zahlung', 0),
  ('290CHF', DATE '2022-05-17', 'Alex Smolders', 'Abo zahlung', 1),
  ('190CHF', DATE '2022-05-17', 'Michael Muster', 'Abo zahlung', 0);
INSERT INTO `person`(`name`, `vorname`, `adresse`, `tel_nummer`, `ort_id`, `rechnung_id`, `verantwortlicher_haushalt`) VALUES
  ('Smolders','Alex','musterstrasse 66','078 654 32 19', 1, 3, null),
  ('Machaz','Severin','kolsterstrasse 66','078 654 32 18', 2, 2, 1),
  ('Muster','Max','kolsterstrasse 66','078 653 32 18', 2, null, 0),
  ('Muster','Micheal','elsestrasse 54','079 641 32 18', 2, 4, null);
INSERT INTO `tarif`(`preis_pro_stunde_nacht`, `preis_pro_stunde_tag`, `kilomoter_unter_100`, `kilometer_ueber_100`) VALUES 
  ('2.70CHF','0.60CHF','0.50CHF','0.25CHF'), 
  ('2.70CHF','0.60CHF','0.54CHF','0.27CHF'), 
  ('2.70CHF','0.60CHF','0.60CHF','0.30CHF');
INSERT INTO `auto`(`name`, `model`, `anz_personen`, `anz_koffer`, `tarif_id`, `manual`) VALUES 
  ('M-Budget','Fiat Panda','5','2', 1, 'm'),
  ('Micro','Smart passion','2','1', 2, 'a'),
  ('Economy','Suzuki Swift','5','3', 3, 'b');   
INSERT INTO `ermahnung` (`datum`, `rechnung_id`) VALUES 
  ('2022-06-02', '2');
INSERT INTO `ausleihe`( `start_timestamp`, `end_timestamp`, `kilometer`, `rechnung_id`, `ort_id` ) VALUES
  ( '2022-04-29 07:00:00', '2022-04-29 09:00:00', '50', 1, 1 );
INSERT INTO `person_auto`(`person_id`, `auto_id`, `ausleihe_id`) VALUES 
  (1, 1, 1);
INSERT INTO `dauer_abonamment`(`person_id`, `abonnament_art_id`, `start_date`, `end_date`) VALUES 
  (1, 1, DATE '2022-05-17', DATE '2023-05-17'),
  (2, 3, DATE '2022-05-17', DATE '2023-05-17'),
  (3, 3, DATE '2022-05-17', DATE '2023-05-17'),
  (4, 2, DATE '2022-03-17', DATE '2023-03-17');