-- MySQL Script generated by MySQL Workbench
-- Sun Jun 26 21:32:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ort`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ort` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ort` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plz` VARCHAR(45) NOT NULL,
  `stadt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `plz_UNIQUE` (`plz` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`abonnament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`abonnament` ;

CREATE TABLE IF NOT EXISTS `mydb`.`abonnament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `preis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idabonnament_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `vorname` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `tel_nummer` VARCHAR(45) NOT NULL,
  `ort_id` INT NOT NULL,
  `abonnament_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ort_id`, `abonnament_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_person_ort_idx` (`ort_id` ASC) VISIBLE,
  INDEX `fk_person_abonnament1_idx` (`abonnament_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_ort`
    FOREIGN KEY (`ort_id`)
    REFERENCES `mydb`.`ort` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_abonnament1`
    FOREIGN KEY (`abonnament_id`)
    REFERENCES `mydb`.`abonnament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tarif` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tarif` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preis_pro_stunde_nacht` VARCHAR(45) NOT NULL,
  `preis_pro_stunde_tag` VARCHAR(45) NOT NULL,
  `kilomoter_unter_100` VARCHAR(45) NOT NULL,
  `kilometer_ueber_100` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`auto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `marke` VARCHAR(45) NOT NULL,
  `anz_personen` INT NOT NULL,
  `anz_koffer` VARCHAR(45) NOT NULL,
  `tarif_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tarif_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_auto_tarif1_idx` (`tarif_id` ASC) VISIBLE,
  CONSTRAINT `fk_auto_tarif1`
    FOREIGN KEY (`tarif_id`)
    REFERENCES `mydb`.`tarif` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rechnung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rechnung` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rechnung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preis` VARCHAR(45) NOT NULL,
  `datum` DATE NOT NULL,
  `anrede` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ausleihe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ausleihe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ausleihe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ort` VARCHAR(45) NOT NULL,
  `start_timestamp` TIMESTAMP NOT NULL,
  `end_timestamp` TIMESTAMP NOT NULL,
  `kilometer` INT NOT NULL,
  `rechnung_id` INT NOT NULL,
  PRIMARY KEY (`id`, `rechnung_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ausleihe_Rechnung1_idx` (`rechnung_id` ASC) VISIBLE,
  CONSTRAINT `rechnung:id`
    FOREIGN KEY (`rechnung_id`)
    REFERENCES `mydb`.`rechnung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`person_auto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`person_auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `auto_id` INT NOT NULL,
  `ausleihe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `person_id`, `auto_id`, `ausleihe_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ausleihe_person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_ausleihe_auto1_idx` (`auto_id` ASC) VISIBLE,
  INDEX `fk_person_auto_ausleihe1_idx` (`ausleihe_id` ASC) VISIBLE,
  CONSTRAINT `fk_ausleihe_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ausleihe_auto1`
    FOREIGN KEY (`auto_id`)
    REFERENCES `mydb`.`auto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_auto_ausleihe1`
    FOREIGN KEY (`ausleihe_id`)
    REFERENCES `mydb`.`ausleihe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ermahnung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ermahnung` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ermahnung` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `rechnung_id` INT NOT NULL,
  PRIMARY KEY (`id`, `rechnung_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ermahnung_rechnung1_idx` (`rechnung_id` ASC) VISIBLE,
  CONSTRAINT `fk_ermahnung_rechnung1`
    FOREIGN KEY (`rechnung_id`)
    REFERENCES `mydb`.`rechnung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
